apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-web-app-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Simple Web App</title>
    </head>
    <body>
        <h1>Welcome to ArgoCD Demo - UPDATED!</h1>
        <p>This is a simple web application deployed using ArgoCD!</p>
        <p>Version: 2.0 - GitOps Flow Test</p>
        <p>Updated: $(date)</p>
    </body>
    </html>